name: Deploy Azure Frontend (Static Web App)

on:
  workflow_dispatch:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend to SWA
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      - name: Build and deploy frontend
        uses: Azure/static-web-apps-deploy@v1
        env:
          NODE_ENV: production
          BASE_URL: https://primecal-backend.ashysea-5001d437.northeurope.azurecontainerapps.io
          FRONTEND_URL: https://app.primecal.eu
          BACKEND_URL: https://primecal-backend.ashysea-5001d437.northeurope.azurecontainerapps.io
          API_URL: https://primecal-backend.ashysea-5001d437.northeurope.azurecontainerapps.io
          FRONTEND_PORT: 443
          BACKEND_PORT: 443
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PRIMECAL_FRONTEND }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend
          api_location: ""
          output_location: dist
